language:
  - cpp
  - python
python:
  - "2.7"
compiler:
  - gcc

before_install:
  - export CI_SOURCE_PATH=$(pwd)
  - sudo sh -c 'echo "deb http://packages.ros.org/ros-shadow-fixed/ubuntu precise main" > /etc/apt/sources.list.d/ros-latest.list'
  - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
  - sudo apt-get update

install:
  - sudo apt-get install python-catkin-pkg python-rosdep
  - sudo rosdep init
  - rosdep update
  - rosdep install --from-paths . --ignore-src --rosdistro hydro -y

before_script:
  - source /opt/ros/hydro/setup.bash
  - mkdir -p ~/frontier_ws/src
  - cd ~/frontier_ws/src
  - catkin_init_workspace
  - ln -s $CI_SOURCE_PATH .  

script:
  - cd ~/frontier_ws
  - catkin_make tests -j1 -DCATKIN_ENABLE_TESTING=ON
  - catkin_make run_tests -j1 -DCATKIN_ENABLE_TESTING=ON
  - catkin_make install -j1 -DCATKIN_ENABLE_TESTING=ON